version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      internal:
        ipv4_address: 172.18.0.10
        aliases:
          - database
          - postgres
      app_net:
        ipv4_address: 172.20.0.10
    dns_search:
      - rsasesorjuridico.com
      - suarez-ramirez
    ports:
      - '5432:5432'
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - database:/var/lib/postgresql/data
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    networks:
      - internal
    command: tunnel --no-autoupdate run --token eyJhIjoiZWQ2NmE1NDZlYWVhMWNlMDBlYjE2YmI1Yzc1NmFkY2EiLCJ0IjoiNjRlN2ZmZjQtZTg1My00OWNjLTljMDgtM2JkOWRlMjk2ZTZlIiwicyI6IlpqY3pNamMyT1RndE1XSXhOUzAwT1RjeExXSmhNV1V0T1RBMFpXUmxZV05qTVdVMiJ9
  app:
    image: app
    hostname: app
    restart: always
    depends_on:
      - postgres
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env.production
    dns:
      - 1.1.1.1
      - 172.64.36.1
      - 172.18.53.53
    dns_search:
      - rsasesorjuridico.com
      - rysasesorjuridico.com
      - suarez-ramirez
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://cachorro_cami:Tengo1amo@cluster0.ffbyjzl.mongodb.net/?retryWrites=true&w=majority
      NODE_ENV: production
    expose:
      - 3000
    networks:
      - internal
      - app_net

volumes:
  database:
    external: true
    name: database
networks:
  internal:
    external: true
    name: internal
  app_net:
    ipam:
      driver: default
      config:
        - subnet: '172.20.0.0/16'
