onlyBuiltDependencies:
  - bcrypt
  - prisma
  - sharp

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  next@>=15.0.0-canary.0 <15.6.0-canary.61: '>=15.6.0-canary.61'
  next@>=15.6.0-canary.0 <15.6.0-canary.59: '>=15.6.0-canary.59'
  next@>=15.6.0-canary.0 <15.6.0-canary.61: '>=15.6.0-canary.61'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
