declare const styles: {
  readonly container: string;
  readonly form: string;
  readonly buttonsRow: string;
  readonly section: string;
  readonly sectionColumn: string;
  readonly sectionRow: string;
  readonly label: string;
  readonly titleInput: string;
  readonly title: string;
  readonly submitButton: string;
  readonly textArea: string;
  readonly vencimientoArea: string;
  readonly selectArea: string;
  readonly button: string;
  readonly icon: string;
  readonly text: string;
  readonly switchBox: string;
  readonly inputElement: string;
  readonly slider: string;
};
export = styles;
