declare const styles: {
  readonly 'container': string;
  readonly 'form': string;
  readonly 'buttonsRow': string;
  readonly 'section': string;
  readonly 'sectionColumn': string;
  readonly 'sectionRow': string;
  readonly 'label': string;
  readonly 'titleInput': string;
  readonly 'title': string;
  readonly 'submitButton': string;
  readonly 'textArea': string;
  readonly 'vencimientoArea': string;
  readonly 'selectArea': string;
  readonly 'editButton': string;
  readonly 'deleteButton': string;
  readonly 'addButton': string;
  readonly 'HomeButton': string;
  readonly 'button': string;
  readonly 'ButtonTextHelper': string;
  readonly 'switchBox': string;
  readonly 'inputElement': string;
  readonly 'slider': string;
  readonly 'dropbtn': string;
  readonly 'dropdown': string;
  readonly 'dropdown-content': string;
  readonly 'link': string;
  readonly 'show': string;
};
export = styles;

