declare const styles: {
  readonly container: string;
  readonly segment: string;
  readonly segmentRowWrap: string;
  readonly segmentRow: string;
  readonly segmentColumn: string;
  readonly segmentDetached: string;
  readonly submitButton: string;
  readonly textArea: string;
  readonly vencimientoArea: string;
  readonly selectArea: string;
  readonly label: string;
  readonly titleInput: string;
  readonly title: string;
  readonly button: string;
  readonly buttonPassive: string;
  readonly buttonActive: string;
  readonly icon: string;
  readonly text: string;
  readonly 'visually-hidden': string;
  readonly switchBox: string;
  readonly thumb: string;
  readonly decor: string;
  readonly inputElement: string;
  readonly slider: string;
};
export = styles;
