// AUTO-GENERATED by `pnpm memoriales:generate-registry` — DO NOT EDIT BY HAND.
// Source: one manifest per file in src/memoriales/manifests/ (excluding types.ts, registry.ts).
/* eslint-disable */
import type { MemorialTemplate } from './types';
import { aportando291y292 } from './aportando-291-y-292';
import { aportandoLiquidacionCredito } from './aportando-liquidacion-credito';
import { base } from './base';
import { impulso_calificacion_demanda } from './impulso_calificacion_demanda';
import { memorial_notificaciones_ley_2213_de_2022_manual_domina_2025 } from './memorial_notificaciones_ley_2213_de_2022_manual_domina_2025';
import { solicitud_oficios_medidas_cautelares } from './solicitud_oficios_medidas_cautelares';
import { terminacion_pago_cuotas_en_mora } from './terminacion_pago_cuotas_en_mora';
import { terminacion_pago_total_de_obligacion } from './terminacion_pago_total_de_obligacion';

/**
 * Lookup map from template id to its `MemorialTemplate` manifest, built from
 * every manifest module discovered under `manifests/`.
 * Auto-generated — do not edit by hand, regenerate via `pnpm memoriales:generate-registry`.
 */
export const memorialesRegistry = {
  [ aportando291y292.id ]: aportando291y292,
  [ aportandoLiquidacionCredito.id ]: aportandoLiquidacionCredito,
  [ base.id ]: base,
  [ impulso_calificacion_demanda.id ]: impulso_calificacion_demanda,
  [ memorial_notificaciones_ley_2213_de_2022_manual_domina_2025.id ]: memorial_notificaciones_ley_2213_de_2022_manual_domina_2025,
  [ solicitud_oficios_medidas_cautelares.id ]: solicitud_oficios_medidas_cautelares,
  [ terminacion_pago_cuotas_en_mora.id ]: terminacion_pago_cuotas_en_mora,
  [ terminacion_pago_total_de_obligacion.id ]: terminacion_pago_total_de_obligacion,
} satisfies Record<string, MemorialTemplate>;

/**
 * Looks up a `MemorialTemplate` by its id in {@link memorialesRegistry}.
 * Used by `actions/generate-memorial.ts` and the template-selector UI to
 * resolve a template id into its manifest.
 * @param id - The template's `id`.
 * @returns The matching `MemorialTemplate`, or `undefined` if no template with that id exists.
 */
export const getTemplateById = ( id: string ): MemorialTemplate | undefined => {
  return ( memorialesRegistry as Record<string, MemorialTemplate> )[ id ];
};
