declare const styles: {
  readonly actuacionDate       : string;
  readonly actuacionDetailsGrid: string;
  readonly actuacionHeader     : string;
  readonly actuacionNote       : string;
  readonly badge               : string;
  readonly badgePrimary        : string;
  readonly badgeSuccess        : string;
  readonly badgeWarning        : string;
  readonly card                : string;
  readonly cardHeader          : string;
  readonly cardSubtitle        : string;
  readonly cardTitle           : string;
  readonly container           : string;
  readonly dataGrid            : string;
  readonly dataItem            : string;
  readonly dataLabel           : string;
  readonly dataValue           : string;
  readonly layout              : string;
  readonly mainPanel           : string;
  readonly procesosGrid        : string;
  readonly sectionTitle        : string;
  readonly sidebarPanel        : string;
  readonly timeline            : string;
  readonly timelineItem        : string;
};
export = styles;
