import { Loader } from '#@/components/Loader';


export default function Loading () {
      return (
        <>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>

        </>
      );
}