declare const styles: {
  readonly container: string;
  readonly card: string;
  readonly section: string;
  readonly date: string;
  readonly actuacion: string;
  readonly anotacion: string;
  readonly fecha: string;
  readonly sub: string;
  readonly dummytxt: string;
  readonly title: string;
  readonly links: string;
  readonly link: string;
  readonly icon: string;
  readonly tooltiptext: string;
  readonly updated: string;
  readonly error: string;
  readonly isActive: string;
  readonly linkIsActive: string;
  readonly notActive: string;
  readonly errorContainer: string;
};
export = styles;
