import '#@/styles/globals.css';
import './manifest';
import type { Metadata } from 'next';
import { ReactNode, Suspense } from 'react';
import layout from '#@/styles/layout.module.css';
import { MainProvider } from './context/main-context';
import { inter, josefina, jost, playDisp, raleway, roboto } from '#@/styles/fonts';
import 'material-symbols';
import { SearchProvider } from './context/search-context';
import { ModalProvider } from './context/modal-context';
import { CarpetaFormProvider } from './context/carpeta-form-context';
import getCarpetas from '#@/lib/project/getCarpetas';

import { CarpetasSortProvider } from './context/carpetas-sort-context';
import { NotasSortProvider } from './context/notas-sort-context';
import getNotas from '#@/lib/project/getNotas';
import Header from 'components/layout/header';
import SearchOutputList from 'components/layout/search/SearchProcesosOutput';
import SearchOutputListSkeleton from 'components/layout/search/SearchProcesosOutputSkeleton';
import Script from 'next/script';


const prefix = process.env.NODE_ENV === 'production'
  ? 'app'
  : 'beta';

const hostname = `https://${ prefix }.rsasesorjuridico.com`;

export const metadata: Metadata = {
  metadataBase: new URL(
    hostname
  ),
  title          : 'R&S Asesoría Jurídica',
  description    : 'Generated by create next app',
  generator      : 'R&S Asesoría Jurídica',
  applicationName: 'R&S Asesoría Jurídica',
  referrer       : 'origin-when-cross-origin',
  colorScheme    : 'light dark',
  keywords       : [
    'Next.js',
    'React',
    'JavaScript'
  ],
  authors: [
    {
      name: 'Camilo Suarez',
    },
    {
      name: 'Cachorro Cami',
      url : hostname,
    },
  ],
  themeColor: [
    {
      media: '(prefers-color-scheme: light)',
      color: '#bb152c',
    },
    {
      media: '(prefers-color-scheme: dark)',
      color: '#ab2a64',
    },
  ],
  creator        : 'Cachorro Cami',
  publisher      : 'CachorroC',
  alternates     : {},
  formatDetection: {
    email    : false,
    address  : false,
    telephone: false,
  },
  openGraph: {
    title      : 'R&S Asesoría Jurídica',
    description: 'The React Framework for the Web',
    url        : hostname,
    siteName   : 'Next.js',
    images     : [
      {
        url   : '/splash_screens/12.9__iPad_Pro_portrait.png',
        width : 800,
        height: 600,
      },
      {
        url   : '/splash_screens/8.3__iPad_Mini_landscape.png',
        width : 1800,
        height: 1600,
        alt   : 'My custom alt',
      },
    ],
    locale: 'es-CO',
    type  : 'website',
  },
  icons: {
    icon: [
      {
        url: '/favicon.ico',
      },
      new URL(
        '/favicon.svg', `${ hostname }`
      ),
    ],
    shortcut: '/icons/safari-pinned-tab.svg',
    apple   : '/icons/safari-pinned-tab.svg',
    other   : {
      rel: 'apple-touch-icon-precomposed',
      url: '/icons/apple-touch-icon-precomposed.png',
    },
  },
  appleWebApp: {
    title         : 'Apple Web App',
    statusBarStyle: 'black-translucent',
    startupImage  : [
      '/icons/mstile-310x310.png',
      {
        url  : '/icons/android-chrome-512x512.png',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },
  appLinks: {
    web: {
      url            : '/',
      should_fallback: true,
    },
  },
};

export default async function RootLayout(
  {
    children,
    modal,
    right,
  }: {
  children: ReactNode;
  modal: ReactNode;
  right: ReactNode;
}
) {
  const carpetas = await getCarpetas();

  const notas = await getNotas();

  return (
    <html lang="es">
      <body className={`${ playDisp.variable } ${ jost.variable } ${ raleway.variable } ${ inter.variable } ${ roboto.variable } ${ josefina.variable }  [ color-scheme: light dark ]`}
      >

        <CarpetasSortProvider carpetas={ carpetas }>
          <NotasSortProvider  notas={ notas}>
            <CarpetaFormProvider>
              <SearchProvider>
                <ModalProvider>
                  <MainProvider>
                    <div className={ layout.container }>
                      <Header>
                        <Suspense fallback={<SearchOutputListSkeleton />}>
                          <SearchOutputList path={ '/Procesos' }/>
                        </Suspense>
                      </Header>
                      {modal}
                      {children}
                      <div className={layout.right}>{right}</div>
                    </div>

                  </MainProvider>
                </ModalProvider>
              </SearchProvider>
            </CarpetaFormProvider>
          </NotasSortProvider>
        </CarpetasSortProvider>
        <Script src={`https://${ prefix }.rsasesorjuridico.com/service-worker.js`}/>
      </body>
    </html>
  );
}
