// generate-registry.ts
// Usage: pnpm memoriales:generate-registry
// Regenerates src/memoriales/manifests/registry.ts from every manifest file found by
// `discoverManifests()`. Run automatically before `next dev`/`next build`; safe to run
// standalone. Only touches disk if the generated output actually changed.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { discoverManifests } from './discover-manifests';

const REGISTRY_PATH = fileURLToPath( new URL(
  '../manifests/registry.ts', import.meta.url
) );

const main = async () => {
  const manifests = await discoverManifests();

  const imports = manifests.map( ( m ) => {
    return `import { ${ m.exportName } } from '${ m.moduleSpecifier.replace(
      '../manifests', '.'
    ) }';`;
  } )
    .join( '\n' );

  const entries = manifests.map( ( m ) => {
    return `  [ ${ m.exportName }.id ]: ${ m.exportName },`;
  } )
    .join( '\n' );

  const generated = `// AUTO-GENERATED by \`pnpm memoriales:generate-registry\` — DO NOT EDIT BY HAND.
// Source: one manifest per file in src/memoriales/manifests/ (excluding types.ts, registry.ts).
/* eslint-disable */
import type { MemorialTemplate } from './types';
${ imports }

export const memorialesRegistry = {
${ entries }
} satisfies Record<string, MemorialTemplate>;

export const getTemplateById = ( id: string ): MemorialTemplate | undefined => {
  return ( memorialesRegistry as Record<string, MemorialTemplate> )[ id ];
};
`;

  const current = ( () => {
    try {
      return readFileSync(
        REGISTRY_PATH, 'utf-8'
      );
    } catch {
      return null;
    }
  } )();

  if ( current === generated ) {
    return;
  }

  writeFileSync(
    REGISTRY_PATH, generated, 'utf-8'
  );
  console.log( `Generated registry.ts with ${ manifests.length } templates.` );
};

main().catch( ( err ) => {
  console.error( err instanceof Error
    ? err.message
    : err );
  process.exit( 1 );
} );
