declare const styles: {
  readonly "Add": string;
  readonly "ButtonTextHelper": string;
  readonly "Delete": string;
  readonly "Edit": string;
  readonly "HomeButton": string;
  readonly "active": string;
  readonly "addButton": string;
  readonly "button": string;
  readonly "buttonsRow": string;
  readonly "checkboxItem": string;
  readonly "container": string;
  readonly "content": string;
  readonly "deleteButton": string;
  readonly "form": string;
  readonly "icon": string;
  readonly "innactive": string;
  readonly "inputElement": string;
  readonly "label": string;
  readonly "nota": string;
  readonly "round": string;
  readonly "section": string;
  readonly "select": string;
  readonly "slider": string;
  readonly "sub": string;
  readonly "submitButton": string;
  readonly "sup": string;
  readonly "switchBox": string;
  readonly "tareas": string;
  readonly "task": string;
  readonly "taskContainer": string;
  readonly "taskList": string;
  readonly "textArea": string;
  readonly "titleInput": string;
};
export = styles;

