declare const styles: {
  readonly 'container': string;
  readonly 'sub': string;
  readonly 'sup': string;
  readonly 'buttonsRow': string;
  readonly 'section': string;
  readonly 'label': string;
  readonly 'titleInput': string;
  readonly 'task': string;
  readonly 'taskContainer': string;
  readonly 'switchBox': string;
  readonly 'inputElement': string;
  readonly 'slider': string;
  readonly 'round': string;
  readonly 'submitButton': string;
  readonly 'icon': string;
  readonly 'textArea': string;
  readonly 'deleteButton': string;
  readonly 'addButton': string;
  readonly 'HomeButton': string;
  readonly 'button': string;
  readonly 'buttonAdd': string;
  readonly 'buttonDelete': string;
  readonly 'buttonEdit': string;
  readonly 'ButtonTextHelper': string;
  readonly 'content': string;
  readonly 'checkboxItem': string;
  readonly 'tareas': string;
  readonly 'select': string;
  readonly 'innactive': string;
  readonly 'active': string;
  readonly 'form': string;
  readonly 'nota': string;
};
export = styles;

