import { Loader } from '../Loader';

export function LefttableLoader () {
      return (
        <>

          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>
          <tr>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
            <td><Loader/></td>
          </tr>


        </>
      );
}