declare const styles: {
  readonly "agregarBloque": string;
  readonly "agregarBloqueDisparador": string;
  readonly "agregarBloqueMenu": string;
  readonly "agregarBloqueOpcion": string;
  readonly "archivadaNota": string;
  readonly "aside": string;
  readonly "bannerLectura": string;
  readonly "bloqueContenido": string;
  readonly "bloqueFila": string;
  readonly "bloques": string;
  readonly "campo": string;
  readonly "campoLabel": string;
  readonly "contador": string;
  readonly "cuerpo": string;
  readonly "editor": string;
  readonly "encabezado": string;
  readonly "errorTexto": string;
  readonly "estadoSelect": string;
  readonly "fijarFila": string;
  readonly "inputError": string;
  readonly "main": string;
  readonly "manija": string;
  readonly "material-symbols-rounded": string;
  readonly "resumenCampo": string;
  readonly "resumenInput": string;
  readonly "seccion": string;
  readonly "seccionTitulo": string;
  readonly "tareas": string;
  readonly "tituloCampo": string;
  readonly "tituloFila": string;
  readonly "tituloInput": string;
  readonly "usuarios": string;
  readonly "vacioTareas": string;
};
export = styles;

