export type Styles = {
  'background': string;
  'backgroundText': string;
  'error': string;
  'errorContainer': string;
  'errorContainerText': string;
  'errorText': string;
  'inverseOnSurface': string;
  'inverseOnSurfaceText': string;
  'inversePrimary': string;
  'inversePrimaryText': string;
  'inverseSurface': string;
  'inverseSurfaceText': string;
  'onBackground': string;
  'onBackgroundText': string;
  'onError': string;
  'onErrorContainer': string;
  'onErrorContainerText': string;
  'onErrorText': string;
  'onPrimary': string;
  'onPrimaryContainer': string;
  'onPrimaryContainerText': string;
  'onPrimaryText': string;
  'onSecondary': string;
  'onSecondaryContainer': string;
  'onSecondaryContainerText': string;
  'onSecondaryText': string;
  'onSurface': string;
  'onSurfaceText': string;
  'onSurfaceVariant': string;
  'onSurfaceVariantText': string;
  'onTertiary': string;
  'onTertiaryContainer': string;
  'onTertiaryContainerText': string;
  'onTertiaryText': string;
  'outline': string;
  'outlineText': string;
  'outlineVariant': string;
  'outlineVariantText': string;
  'primary': string;
  'primaryContainer': string;
  'primaryContainerText': string;
  'primaryText': string;
  'scrim': string;
  'scrimText': string;
  'secondary': string;
  'secondaryContainer': string;
  'secondaryContainerText': string;
  'secondaryText': string;
  'shadow': string;
  'shadowText': string;
  'surface': string;
  'surfaceText': string;
  'surfaceTint': string;
  'surfaceTintText': string;
  'surfaceVariant': string;
  'surfaceVariantText': string;
  'tertiary': string;
  'tertiaryContainer': string;
  'tertiaryContainerText': string;
  'tertiaryText': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
